import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";

import NavBar from "../components/NavBar";
import Card from "../components/project/Card";
import imageLoader from "../imageLoader";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Théo Bori</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className="mx-auto max-w-[40%]">
        <div className="text-2xl font-bold">
          About
        </div>
        <ul role="list" className="my-4 marker:text-teal-500 list-disc">
          <li>
            EPITECH student
          </li>
          <li>
            Open source enthoutiast
          </li>
          <li>
            <a className="mr-1">
              <Image 
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Emoji_u2665.svg/1024px-Emoji_u2665.svg.png"
                alt="heart"
                width="20px"
                height="20px"
                loader={imageLoader}
                unoptimized
                >
              </Image>
            </a>
            Rust
          </li>
        </ul>

        <div className="text-2xl font-bold">
          Profiles
        </div>
        <ul role="list" className="my-4 marker:text-teal-500 list-disc">
          <li>
            <a href="https://www.github.com/theobori" className="text-teal-500 hover:underline">
            GitHub
            </a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/theo-bori/" className="text-teal-500 hover:underline">
            LinkedIn
            </a>
          </li>
        </ul>

        <div className="text-2xl font-bold">
          Some Open Source projects
        </div>
        <ul role="list" className="my-4 marker:text-teal-500 list-disc">
          <li>
            <Card langage="Project card 1"/>
          </li>

          <li>
            <Card langage="Project card 2"/>
          </li>

        </ul>
  
      </div>

    </div>
  );
};

export default Home;
